### ISSUE TITLE
broken link to latest release

### ISSUE THREAD

**Issue by ArminGuntram** [spectra-cluster/spectra-cluster-py#4]
Hi, 
The link to:
https://github.com/spectra-cluster-py/releases
appears to be broken.

I did download a .zip from:
https://github.com/spectra-cluster/spectra-cluster-py
and extracted the contents.

Can I install this on a windows machine?

In the readme there is a line:
"You can find the spectra-cluster-py's documentation at *Read the Docs*." 
Where/which are the docs that are being referred to?

Thank you in advance
-Armin

**Comment by jgriss** [comment]
Hi Armin,

Sorry about the late response!!!

Yes, the package works on any system supported by python. Simply extract the zip file, open a command prompt and navigate to the "spectra_cluster" folder and install the package by typing `pip install ./`

About the broken link: Could you tell me where you found it?

The docs can be found at http://spectra-cluster-py.readthedocs.io/en/latest/

The link can also be found in the README.rst file of the project.

Finally, only note that this package is only intended to **analyse** clustering results. To actually cluster MS/MS data you'd have to use the [spectra-cluster-cli](https://github.com/spectra-cluster/spectra-cluster-cli) tool.

**Comment by ArminGuntram** [comment]
Hi,

Thank you for the reply!

My apologies, here is the url for the broken link:
https://github.com/spectra-cluster-py/releases

I was able to find all the information I needed to parse the .clustering
files.

I do have a question regarding the precursor tolerance and fragment
tolerance used when running spectra-cluster-cli:

Currently the default is is set at 2.0 and 0.5 m/z units for precursor -
and fragment tolerance respectively. Is there any particular reason why I
should stick to these values?

This tutorial:
https://spectra-cluster.github.io/tutorials/clustering_basics.html
says that I can adjust the tolerances according to the mass spectrometers
accuracy.

The data I'm working with is considered high mass accuracy in both MS1 and
MS2.
The MS1 tolerance is 0.005 and the MS2 is 0.01 (m/z units).

I've run spectra-cluster-cli with these (0.005 and 0.01) parameters as well
as a range up to and including the default values. Expectedly compute time
decreases quite a bit, however the number of cluster that are output by the
program decreases by more than 50% ( at tolerances 0.005 and 0.01).

Does the precursor mass tolerance need to remain relatively large in order
to account for the possibility of peptides of the same sequence occurring
in different isotopic states?

Kind Regards,
-Armin

**Comment by jgriss** [comment]
Hi,

Thanks for the info! I'll fix the link ASAP. Btw. if you have any feedback / complaints about the tutorial just let me know! I'm happy to add / adjust it!

## Precursor and fragment tolerance
Both can and should be set to your data's properties. The default values only come from the settings we use to build the PRIDE Cluster resource. There, we also had to consider old IonTrap data. Now, that high resolution data is becoming the standard, this might be changed.

Because of that, in the current development version of the [spectra-cluster-cli](https://github.com/spectra-cluster/spectra-cluster-cli) tool the precursor tolerance can also be set in ppm.

## Issue of decreasing clusters

This is caused by the empirical cumulative distribution function we use to estimate the final precision during clustering. This was based on low-resolution settings. In high-resolution data, you actually get much higher cluster precisions than the one you set.

Here's what you can do to change that:
* Use different settings for the `-x_min_comparisons` parameter. I'd suggest to actually set this to `0` if you're data is very clean
* Double check the clustering accuracy by integrating identification data into your clustering process. This will give you a worst-case estimate of the actual accuracy you got. I'm happy to send you a python script to do this.

Because of these issues I'm currently working on getting the tool to adjust these settings automatically to the processed dataset. But unfortunately, this is still ongoing.

If you test different parameters for the clustering, you can speed up the process dramatically:
1. Set a permanent temporary directory using the `-binary_directory` parameter
2. Keep the binary files after clustering by setting the `-keep_binary_files` parameter
3. Reuse the generated binary files by setting the `-reuse_binary_files` parameter
    **Warning:** If you set this parameter, the used precursor tolerance must not be increased!

This will cause the tool to not convert the input files again and can save you quite a lot of time between the individual clustering runs.

If any of these steps are unclear, just ask!

Best regards,
Johannes

**Comment by jgriss** [comment]
I just released to answer you second question:

> Does the precursor mass tolerance need to remain relatively large in order to account for the possibility of peptides of the same sequence occurring in different isotopic states?

Yes. If you want to detect these as well, you have to increase the precursor tolerance. What I currently do is to set the fragment tolerance to my instrument's one and then use a precursor tolerance between 1-2 *m/z*.

But this of course depends on your use case.

**Comment by ArminGuntram** [comment]
Hi Johannes,

Thank you very much for your response and the information.

If you could share the python script that you use to integrate the
identification data into the clustering process that would be great!

I've attached 5 text files containing summaries of spectra-cluster outputs
produced using different program parameters. All the jobs were run on the
same set of 72 .mgf files. Each of the attached text files have the spectra
cluster command and specified program options as well as the  consequent
console output. This is followed by a short summary of the produced
clusters.

Are these outputs inline with what you normally see from similar datasets?
Is it normal to have such a large proportion of singlet clusters?

Based on the information that you've provided thus far I would like to
proceed with the resulting clusters from running spectra-cluster with:

Precursor tolerance: 2.0
Fragment ion tolerance: 0.01
-use_cdf
-x_min_comparisons 0

I can provide additional information about the data if you need?

Thank you in advance

-Armin

ps. I've added myself (work email) and the email of Dr.Paul Abraham
(Bioanalytical Chemist, Oak Ridge National Lab) to the cc list.

**Comment by jgriss** [comment]
Hi Armin,

Since you replied to the GitHub issue, this was posted as a reply to the topic on GitHub and your e-mail information (including any CCs) was removed.

In case this wasn't intended, you or I can delete your comment. Maybe you can simply send me an e-mail at johannes.griss@meduniwien.ac.at

Thanks a lot!

Johannes
